[placeholders.command_name]
type = "string"
prompt = "What should your first command be called? (spaces are okay)"

[placeholders.multi_command]
type = "string"
prompt = "Do you intend to create more than one command / subcommand?"
choices = [
  "Yes",
  "No"
]
default = "No"

[placeholders.command_is_simple]
type = "string"
prompt = "Would you like a simple command? Say no if you would like to use streaming."
choices = [
  "Yes",
  "No"
]

[placeholders.github_username]
type = "string"
prompt = "What is your GitHub username? (Leave blank if you don't want to publish to GitHub)"
default = ""

[hooks]
init = ["init.rhai"]
pre = ["pre.rhai"]

[conditional.'multi_command == "No"']
ignore = ["src/commands"]
